#!/system/bin/sh

#     _             _     _ _  __                    _
#    / \   _ __ ___| |__ (_) |/ /___ _ __ _ __   ___| |
#   / _ \ | '__/ __| '_ \| | ' // _ \ '__| '_ \ / _ \ |
#  / ___ \| | | (__| | | | | . \  __/ |  | | | |  __/ |
# /_/   \_\_|  \___|_| |_|_|_|\_\___|_|  |_| |_|\___|_|
#
# Copyright 2015 Łukasz "JustArchi" Domeradzki
# Contact: JustArchi@JustArchi.net
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Read -> generic
# Write -> ON/OFF switch, with response to stdout

SYSFS_CPU="/sys/devices/system/cpu/cpu${1}"

if [[ -f "$SYSFS_CPU/online" ]]; then
	if [[ "$(cat "$SYSFS_CPU/online")" -eq 0 ]]; then
		echo "1" > "$SYSFS_CPU/online"
		echo "CPU${1} Online!"
	else
		echo "0" > "$SYSFS_CPU/online"
		echo "CPU${1} Offline!"
	fi
else
	echo "0"
fi
