#!/system/bin/sh

#     _             _     _ _  __                    _
#    / \   _ __ ___| |__ (_) |/ /___ _ __ _ __   ___| |
#   / _ \ | '__/ __| '_ \| | ' // _ \ '__| '_ \ / _ \ |
#  / ___ \| | | (__| | | | | . \  __/ |  | | | |  __/ |
# /_/   \_\_|  \___|_| |_|_|_|\_\___|_|  |_| |_|\___|_|
#
# Copyright 2015 Łukasz "JustArchi" Domeradzki
# Contact: JustArchi@JustArchi.net
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Read -> return current preset from $1. Special: return all presets if $1 is "ALL"
# Write -> set $2 preset in $1

SYSFS_FILE="$1"
TARGET_VALUE="$2"

# Knows presets
KNOWN_PRESETS="Archi BaseLand BassExtreme BassTreble Classic Dance Eargasm Flat Pleasant Rock Treble"
ALL_PRESETS="$KNOWN_PRESETS Custom"

PRESET_Archi="8 4 4 2 6"
PRESET_BaseLand="8 7 4 3 3"
PRESET_BassExtreme="12 8 3 -1 1"
PRESET_BassTreble="10 7 0 2 5"
PRESET_Classic="0 0 0 -3 -5"
PRESET_Dance="4 0 -6 0 3"
PRESET_Eargasm="12 8 4 2 3"
PRESET_Flat="0 0 0 0 0"
PRESET_Pleasant="4 3 2 2 3"
PRESET_Rock="4 3 0 -4 3"
PRESET_Treble="-5 1 0 4 3"

if [[ "$SYSFS_FILE" = "ALL" ]]; then
	echo "$ALL_PRESETS"
elif [[ -e "$SYSFS_FILE" ]]; then
	if [[ -z "$TARGET_VALUE" ]]; then # Read mode
		GAINS_CURRENT="$(tr -d '[:alpha:]' < "$SYSFS_FILE" | tr -d '[:punct:]')"
		FOUND=0
		for PRESET_CHOSEN in $KNOWN_PRESETS; do
			eval PRESET_VALUES="\${PRESET_${PRESET_CHOSEN}}" # eval is evil
			if [[ "$GAINS_CURRENT" = *"$PRESET_VALUES" ]]; then
				echo "$PRESET_CHOSEN"
				FOUND=1
				break
			fi
		done
		if [[ "$FOUND" -eq 0 ]]; then
			echo "Custom"
		fi
	else # Write mode
		if [[ "$TARGET_VALUE" != "Custom" ]]; then
			eval SYSFS_WRITE="\${PRESET_${TARGET_VALUE}}" # eval is evil
			if [[ -n "$SYSFS_WRITE" ]]; then
				echo "$SYSFS_WRITE" > "$SYSFS_FILE" # Write effect
			fi
		fi
	fi
else
	echo "0"
fi
