#!/system/bin/sh

#     _             _     _ _  __                    _
#    / \   _ __ ___| |__ (_) |/ /___ _ __ _ __   ___| |
#   / _ \ | '__/ __| '_ \| | ' // _ \ '__| '_ \ / _ \ |
#  / ___ \| | | (__| | | | | . \  __/ |  | | | |  __/ |
# /_/   \_\_|  \___|_| |_|_|_|\_\___|_|  |_| |_|\___|_|
#
# Copyright 2015 Łukasz "JustArchi" Domeradzki
# Contact: JustArchi@JustArchi.net
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Read -> return current status (alive) of the service/process
# Write -> start/stop given service/process, if needed

if [[ -n "$1" ]]; then
	BIN_PATH="$(which "$1")"
	if [[ -f "$BIN_PATH" ]]; then
		if pidof "$1" >/dev/null 2>&1; then
			PROCESS_ALIVE=1
		else
			PROCESS_ALIVE=0
		fi
		if [[ -n "$2" ]]; then
			if [[ "$2" -eq 1 && "$PROCESS_ALIVE" -eq 0 ]]; then
				start "$1"
			elif [[ "$2" -eq 0 && "$PROCESS_ALIVE" -eq 1 ]]; then
				stop "$1"
			fi
		else
			echo "$PROCESS_ALIVE"
		fi
	else
		echo "0"
	fi
else
	echo "0"
fi
