#!/system/bin/sh

#     _             _     _ _  __                    _
#    / \   _ __ ___| |__ (_) |/ /___ _ __ _ __   ___| |
#   / _ \ | '__/ __| '_ \| | ' // _ \ '__| '_ \ / _ \ |
#  / ___ \| | | (__| | | | | . \  __/ |  | | | |  __/ |
# /_/   \_\_|  \___|_| |_|_|_|\_\___|_|  |_| |_|\___|_|
#
# Copyright 2015 Łukasz "JustArchi" Domeradzki
# Contact: JustArchi@JustArchi.net
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Read -> return current value from $1 for given $2 channel
# Write -> set $3 value for given $2 channel in $1

SYSFS_FILE="$1"
TARGET_TYPE="$2"
TARGET_VALUE="$3"

if [[ -e "$SYSFS_FILE" ]]; then
	case "$TARGET_TYPE" in
		L) TARGET_TYPE="2" ;;
		R) TARGET_TYPE="3" ;;
	esac

	if [[ -z "$TARGET_VALUE" ]]; then # Read mode
		awk "FNR == $TARGET_TYPE {print \$NF}" < "$SYSFS_FILE" # Synapse return
	else # Write mode
		if [[ "$TARGET_TYPE" -eq 2 ]]; then # Left
			SYSFS_WRITE="$TARGET_VALUE $(awk 'FNR == 3 {print $NF}' < "$SYSFS_FILE")"
		else # Right
			SYSFS_WRITE="$(awk 'FNR == 2 {print $NF}' < "$SYSFS_FILE") $TARGET_VALUE"
		fi
		echo "$SYSFS_WRITE" > "$SYSFS_FILE" # Write effect
	fi
else
	echo "0"
fi
