#!/system/bin/sh

#     _             _     _ _  __                    _
#    / \   _ __ ___| |__ (_) |/ /___ _ __ _ __   ___| |
#   / _ \ | '__/ __| '_ \| | ' // _ \ '__| '_ \ / _ \ |
#  / ___ \| | | (__| | | | | . \  __/ |  | | | |  __/ |
# /_/   \_\_|  \___|_| |_|_|_|\_\___|_|  |_| |_|\___|_|
#
# Copyright 2014-2015 Łukasz "JustArchi" Domeradzki
# Contact: JustArchi@JustArchi.net
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

BACKGROUND=0

# Parse ARGs
for ARG in "$@"; do
	case "$ARG" in
		--background) BACKGROUND=1 ;;
	esac
done

if [[ "$BACKGROUND" -eq 0 ]]; then
	"$0" "--background" "$@" &
	exit 0
fi

AK="/data/.ArchiKernel"
mkdir -p "$AK"

LOG="$AK/ArchiKernel.log"
exec 1>"$LOG"
exec 2>&1

LASTVERSION="$AK/version.txt"
VERSION="$(tr -d '#' < /proc/version)"

date
echo "ArchiKernel-Init called!"
echo "Version: $VERSION"

# Regenerate config if needed
#if [[ ! -f "$LASTVERSION" || "$(cat "$LASTVERSION")" != "$VERSION" ]]; then
	echo "NOTICE: Detected new version, regenerating config.json!"
	uci reset
	echo "$VERSION" > "$LASTVERSION"
#fi

echo "ArchiKernel-Init finished!"
date
exit 0
